version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"

sphinx:
   configuration: docs/conf.py
   builder: html
   fail_on_warning: false

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
