# generated by datamodel-codegen:
#   filename:  msticpyconfig-schema.json
#   timestamp: 2023-04-29T00:05:02+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from uuid import UUID

from pydantic import AnyUrl, BaseModel, Extra


class Model(BaseModel):
    __root__: Any


class SentinelWorkspace(BaseModel):
    """Azure Sentinel Workspace configuration."""
    TenantId: UUID
    WorkspaceId: UUID
    SubscriptionId: Optional[UUID] = None
    ResourceGroup: Optional[str] = None
    WorkspaceName: Optional[str] = None


class ProtectedValueEnv(BaseModel):
    """Protected environment variable definition."""
    EnvironmentVar: str


class ProtectedValueKv(BaseModel):
    """Protected KeyVault secret definition."""

    KeyVault: Optional[str]


class ProtectedValue(BaseModel):
    """Protected value definition."""

    __root__: Union[str, ProtectedValueEnv, ProtectedValueKv]


class Args(BaseModel):
    """Provider Args definition."""
	
    class Config:
        extra = Extra.allow

    AuthKey: Optional[ProtectedValue] = None
    AuthId: Optional[ProtectedValue] = None
    ClientId: Optional[ProtectedValue] = None
    TenantId: Optional[ProtectedValue] = None
    ClientSecret: Optional[ProtectedValue] = None
    Cluster: Optional[AnyUrl] = None
    IntegratedAuth: Optional[bool] = True
    Database: Optional[str] = None


class KustoCluster(BaseModel):
    """Kusto cluster definition."""	

    ClusterGroups: Optional[List[str]] = None
    Args: Args


class TIProvider(BaseModel):
    """Threat Intelligence provider definition."""

    Args: Optional[Args]
    Primary: bool
    Provider: str


class DataProvider(BaseModel):
    """Data provider definition."""	

    Args: Optional[Args]
    Provider: Optional[str]


class AzureCloud(Enum):
    """Azure cloud definition."""
    global_ = 'global'
    cn = 'cn'
    de = 'de'
    usgov = 'usgov'
    ppe = 'ppe'
    us = 'us'


class AuthMethod(Enum):
    """Authentication method definition."""
    env = 'env'
    cli = 'cli'
    msi = 'msi'
    vscode = 'vscode'
    powershell = 'powershell'
    interactive = 'interactive'
    interactive_browser = 'interactive_browser'
    devicecode = 'devicecode'
    device_code = 'device_code'
    device = 'device'
    environment = 'environment'
    managedidentity = 'managedidentity'
    managed_identity = 'managed_identity'
    clientsecret = 'clientsecret'
    client_secret = 'client_secret'
    certificate = 'certificate'
    cert = 'cert'


class Azure(BaseModel):
    """Azure configuration definition."""
    cloud: Optional[AzureCloud] = 'global'
    auth_methods: List[AuthMethod]


class KeyVault(BaseModel):
    """KeyVault definition."""

    VaultName: str
    ResourceGroup: Optional[str] = None
    SubscriptionId: Optional[UUID] = None
    TenantId: UUID
    AzureRegion: Optional[str] = None
    UseKeyring: Optional[bool] = False
    Authority: Optional[AzureCloud] = 'global'


class QueryDefinitions(BaseModel):
    """Query definition definition."""	

    Custom: Optional[List[str]] = None

class SentinelWorkspaces(BaseModel):
    """Azure Sentinel Workspaces definition."""	

    Workspaces: Optional[Dict[str, SentinelWorkspace]] = None

class ProxyDefinition(BaseModel):
    """Proxy definition."""	

    Url: str
    UserName: Optional[ProtectedValue] = None
    Password: Optional[ProtectedValue] = None

class Proxies(BaseModel):
    """Proxies definition."""	

    Https: ProxyDefinition
    Http: Optional[ProxyDefinition] = None

class Logging(BaseModel):
    """Logging definition."""	
    LoggingLevel: Optional[str] = 'Info'
    FileName: Optional[str] = None
    

class MsticpyGlobal(BaseModel):
    """Msticpy global configuration definition."""	

    FriendlyExceptions: Optional[bool] = True
    Proxies: Optional[Proxies] = None
    Logging: Optional[Logging] = None
    HttpTimeout: Union[float, Iterable[float,...], Dict[str, Float]] = 30


class MsticpyConfigSchema(BaseModel):
    """Msticpy configuration definition."""	
    msticpy: Optional[MsticpyGlobal] = None
    AzureSentinel: Optional[SentinelWorkspaces] = None
    Azure: Optional[Azure] = None
    KustoClusters: Optional[Dict[str, KustoCluster]] = None
    TIProviders: Optional[Dict[str, TIProvider]] = None
    DataProviders: Optional[Dict[str, DataProvider]] = None
    OtherProviders: Optional[Dict[str, DataProvider]] = None
    ContextProviders: Optional[Dict[str, DataProvider]] = None
    QueryDefinitions: Optional[QueryDefinitions] = None
    KeyVault: Optional[KeyVault] = None